version: '2'
services:
    web:
        container_name: web
        image: nginx:latest
        expose:
            - "9000"
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - ./conf.d/:/etc/nginx/conf.d/
        links:
            - php
            - redis
            - memcached
    php:
        container_name: php
        build: ./.docker/images/php-fpm
        volumes:
            - ./.docker/images/php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ./www:/www
    redis:
        image: redis
        ports:
        - "6379:6379"
    memcached:
        image: memcached
        ports:
        - "11211:11211"