version: '2'
services:
    web:
        container_name: web
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./www:/www
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        container_name: php
        image: php:5.6-fpm
        volumes:
            - ./www:/www
            